# -*- coding: utf-8 -*-
"""Assignmen1 -Archita_Teachnook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ZTENQN846CNF2xCYl2IWaTclsB392FT
"""

#Assingment 1- 2 EXAMPLES OF COLLECTIVE DATA TYPES

#LIST

list_1=["Hello","World",1,3.4,"Archita"]
print(list_1)

list_1[1]="Python"
print(list_1)

list_1.append("25")
print(list_1)

list_2=["strings","Archita","blue","yellow"]
list_1.extend(list_2)
print(list_2)

print(list_1)

list_1.remove("Hello")
print(list_1)

#TUPLE - Immutable

tup={"Archita","blue",14,"black",54}
print(tup)

len(tup)

newtup={"Hello","I","am","Archita",24,8}
print(newtup)
print(len(newtup))

#Dictionary

mydict={"ID":"Archita","password":"Riya","College":"SRMIST","Year":"2025"}
print(mydict)

mydict["ID"]=("Archita","Sinha")
mydict["password"]=("srm","ist")
mydict["college"]=("SRM","KIIIT")
mydict["Year"]=("2024","2025")

print(mydict)

del(mydict["password"])
print(mydict)

mydict["password"]=("Riya",14)
print(mydict)

#SET -- 

myset={"Archita",24,"sinha",14,5.6}
print(myset)

set_1={67,5.6,14,2003,9,8,11}
set_2={45,89,78,678,985,65}
print(len(set_1))
print(len(set_2))

set3=set_1.union(myset)
print(set3)

set4=set_1|set_2
print(set4)

set4.add("Hiiii")
print(set4)

#ASSIGNMENT 2 -FILE READ,WRITE,APPEND

file=open("s.txt","w")
file.write("Hello World , sky is blue")

file=open("try.txt","r")
print(file.read())

file=open("try.txt","a")
file.write("\nI love Python")

file=open("try.txt","r+")
print(file.read())